### ISSUE TITLE
SQL server deadlocks on grants/drops

### ISSUE THREAD

**Issue by jasonodonnell** [microsoft/go-mssqldb#102] opened 2023-05-08 15:16 UTC
Hi from HashiCorp! 👋 

I don't suspect any bugs with this driver, but wanted to ask since documentation around `Sch-m` seems limited. Vault uses this driver in our database secret engine implementation for SQL server. We've noticed really poor performance with this secret engine which is seemingly due to a `Sch-M` deadlock on `SECURITY_CACHE` when [generating dynamic users](https://developer.hashicorp.com/vault/docs/secrets/databases/mssql#setup). These appear to come from grants and drops (Vault runs these when revoking users).

A benchmark of the secret engine shows very poor performance with most requests taking up to 20 seconds:
```
Target: http://127.0.0.1:8200
op            count  rate      throughput  mean          95th%          99th%          successRatio
mssql_test_1  217    3.724721  2.828874    2.415913128s  15.624439266s  21.835062543s  100.00%
```

Is this expected when granting and dropping permissions? Is there anything we can do on the driver side to avoid this? I doubt there is but wanted to ask nontheless. 😅

**Comment by shueybubbles** [comment] 2023-05-08 19:09
thx for opening an issue.
Have you compared this behavior with running an equivalent script that uses the ODBC sqlcmd to run the same commands?

**Comment by shueybubbles** [comment] 2023-05-08 19:20
And have you captured any query plans from the slow executions?

**Comment by jasonodonnell** [comment] 2023-05-09 14:24
@shueybubbles Thanks for the quick reply. I have compared it to a SQL client but I believe Vault's use case is slightly different:
* Vault takes in SQL statements as a creation_statement from the operator. This is free form and operators can use a templating language where Vault will insert generated values such as usernames and passwords. Vault takes this SQL and runs all of it in a transaction. We do this so we can recover from partial failures via rollbacks. When I run this with a SQL client in a transaction.
* The scale of Vault is much larger. Users will be creating SQL server users on demand and when the TTLs of those users expire, Vault revokes them. This increases the likelyhood of deadlocking (work around is configuring LOCK_TIMEOUT to some positive integer but its then on the clients to retry).

I haven't run a query plan but I can look into getting that. Candidly my SQL server knowledge are lacking 😅

**Comment by jasonodonnell** [comment] 2023-05-09 14:26
Example SQL might look like:

```sql
 CREATE LOGIN [{{name}}] WITH PASSWORD = '{{password}}';
 
 GRANT VIEW SERVER STATE TO [{{name}}];

 USE [10029_Example];

  CREATE USER [{{name}}] FOR LOGIN [{{name}}];

  GRANT SELECT, EXECUTE ON DATABASE::[10029_Example] TO [{{name}}];

  GRANT INSERT, UPDATE, DELETE ON SCHEMA::dwars TO [{{name}}];

  GRANT VIEW DEFINITION TO [{{name}}];
```

**Comment by overachiever-productions** [comment] 2023-05-09 18:46
@jasonodonnell I don't remember being able to solve the exact root-cause of this - or create a work-around (but might have - it's been a few years at this point since I last saw this). But I have seen the EXACT error/problem you're seeing - DROPs and CREATEs causing significant lag/contention. 

Some things you could do to help 'prove' this is a bug: 
- Try this same scenario against a BRAND NEW SQL Server instance (e.g., install SQL Server 2022, and the latest CUs - with NO existing logins/etc.). My guess/expectation is that you will NOT see the problem. 
- Then, add roughly 5K or even 10K SQL Auth Logins (I can't remember if this issue ONLY applied to SQL Auth logins or ALL logins - and, obviously, waaaaay harder to test/generate ~5K 'windows' logins)... and see if the problem occurs. 
- This problem SHOULD be reproducible with a few 1000 logins on-box. 
- I BELIEVE there's also a damned good chance that after you can repro the problem with a few K logins, that DROPing those bogus logins ... won't fix the problem? (or maybe I'm seriously mis-remembering?)

I'm pretty sure this is a problem 'at scale' with SQL Server engine spending too much time having to (correctly) review underlying clerks/caches for specifics being DROP'd (i.e., navel-gazing/inefficient lookups at scale) being the primary issue - and only happening when there are significant #s of logins. 

I also have a VAGUE memory of attempting to use `DBCC FREESYSTEMCACHE('TokenAndPermUserStore');` as a potential means for getting around this issue - but can't remember if it worked. (Worth a try... but even if you're dumping this and even IF it helps, there's going to be, presumably, a corresponding hit/negative in terms of security lookups down the road.)

**Closed** 2023-05-15 15:24 UTC
